import Head from "next/head";
import Image from "next/image";
import LogoComponent from "../../components/Header/LogoComponent";
import FormComponent from "../../components/Login/FormComponent";
import styles from "./styles.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Giphy APP - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <LogoComponent width={750} />
      </header>

      <main className={styles.main}>
        <FormComponent />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
